### ISSUE TITLE
The HR@50 is only 0.18 for movieLens_1M

### ISSUE THREAD

**Issue by farewong** [hanliu95/HS-GCN#2]
I can't reproduce the result of the paper.  Is this due to dataset splitting? thank you

**Comment by hanliu95** [comment]
Thank you for your question. It is highly likely that the issue is caused
by dataset splitting, given that the original data consists of explicit
ratings. Additionally, I recall that there were instances where a one-layer
HS-GCN achieved better performance.

farewong ***@***.***> 于2023年3月27日周一 15:54写道：
